/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import domain.Analista;
import domain.Departamento;
import domain.Empleado;
import domain.JefeProyecto;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import utils.Empresa;

/**
 *
 * @author Christian
 */
public class RegistroDatos extends javax.swing.JDialog {

    private Empresa empresa = null;
   

    public RegistroDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public RegistroDatos(Empresa empresa) {
        this(null, true);
        this.empresa = empresa;        
        this.setLocationRelativeTo(null);
        showTable();
    }

    public void showTable() {
        String[] colsNames = {"Nombre", "Ausencias", "Rol", "Descuento", "Jaba de aseo"};
        List<Empleado> empleados = empresa.getEmpleados();

        DefaultTableModel model = new DefaultTableModel(colsNames, empleados.size());

        jTable5.setModel(model);

        int row = 0;
        for (Empleado e : empleados) {
            model.setValueAt(e.getNombre(), row, 0);
            model.setValueAt(e.getAusencias(), row, 1);
            
            if (e instanceof JefeProyecto) {
                model.setValueAt("Jefe de Proyecto", row, 2);
            } else if (e instanceof Analista) {
                model.setValueAt("Analista", row, 2);
            } else {
                model.setValueAt("Programador", row, 2);
            }
            
            if(e instanceof Empleado){
                model.setValueAt(empresa.trabajadorDescuentoAusencia(e.getNombre()) + "%" , row, 3);
            }
            if(e instanceof Empleado){
               int j = empresa.trabajadorJabaAseo(e.getNombre());
                if (j == 1){
                    model.setValueAt("SI", row, 4);
                } else 
                    model.setValueAt("NO", row, 4); 
            }
            row++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de datos");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jTable5ComponentRemoved(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 847, 468));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable5ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable5ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable5ComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroDatos dialog = new RegistroDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
